### ISSUE TITLE
Implement AS923 and SK920-923 Bands

### ISSUE THREAD

**Issue by htdvisser** [brocaar/lorawan#18]
On 15 November, the LoRa Alliance released the **LoRaWAN 1.0.2 Specification** and **LoRaWAN Regional Parameters 1.0** that includes specifications for the Asian 923 MHz bands and the South Korean 920-923 MHz band. 

Shouldn't be much work to implement these in the `band` package. Let me know if I can help with this.

**Comment by brocaar** [comment]
Thanks for letting me know! I'll update the package in the coming days :-)

**Comment by brocaar** [comment]
@htdvisser, I started working on the AS923 band (after that I'll implement the SK920-923 band too), but there are some structural changes I need to make in order to support this config:

- Currently the `RX1DataRate` is a lookup table, this needs to be refactored into a function to support the logic described in **2.7.7**
- DwellTime will be a new argument for the `band.GetConfig` function

Since I'm breaking the `band.GetConfig` api, I'll also add a `repeaterCompatible`

If you would be able to review the changes afterwards and final-check the values, that would be great.

**Comment by brocaar** [comment]
@htdvisser I've finished working on the AS923 + KR920-923 branch / pull-request. Could you do a final check on the values?

**Comment by brocaar** [comment]
Thanks for reviewing. I've merged the changes into master.
